package edu.kit.ifv.core.statemachine
/**
 * Interface representing an agent that can process [Event]s and [Message]s.
 * Agents are the core entities in the event-based simulation that process and send events.
 *
 * @param M The type of message this agent can process
 */
interface Agent<M : Message> {

    /**
     * Initializes the agent and returns any events/messages produced during initialization.
     *
     * @return Events in response to agent initialization
     */
    fun init(): Events

    /**
     * Processes an [Event] containing a [Message] and produces new [Event]s in response.
     *
     * @param event The event to be processed
     * @return Events produced in response to the given event
     */
    fun processEvent(event: Event<out M>): Events
}

/**
 * An agent implementation that uses a state machine to manage its behavior.
 * This interface provides default implementations for init and processEvent methods
 * that delegate to the state machine.
 *
 * @param M The type of message this agent can process
 */
interface StateBasedAgent<M : Message> : Agent<M> {
    /** The state machine that manages this agent's behavior. */
    val stateMachine: StateMachine

    /**
     * Initialize the agent by starting its state machine.
     * Returns [Event]s produced during onEnter of initial state.
     *
     * @return Events generated by starting the state machine
     */
    override fun init(): Events = stateMachine.start()

    /**
     * Process the given [Event] by delegating to the state machine.
     *
     * @param event The [Event] to process
     * @return [Event]s generated by the state machine in response to the given event
     */
    override fun processEvent(event: Event<out M>): Events = stateMachine.process(event)
}
