variables:
  MOBITOPP_COMMIT_HASH: $CI_COMMIT_SHA

default:
  image: amazoncorretto:25

stages: # List of stages for jobs, and their order of execution
  - build
  - test
  - publish
#Removed for syncing public publication processes.
#include:
#  # trigger downstream projects and create version number
#  - local: gitlab-pipeline/downstream_based_version_number.yml

build-job:
  stage: build
  script:
    - ./gradlew compileKotlin
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - build/

test-job:
  stage: test
  needs: [ build-job ]
  script:
    - ./gradlew test koverXmlReport koverLog
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
      coverage_report:
        coverage_format: cobertura
        path: build/reports/kover/report.xml

    paths:
      - build/reports/kover/*
  coverage: "/application line coverage: ([0-9]+\\.?[0-9]*)%/"

code-style:
  stage: test
  needs: [ build-job ]
  script:
    - ./gradlew detektGenerateConfig
    - ./gradlew detekt

deploy-job:
  stage: publish
  only:
    - main
    - master
  needs: [ "test-job" ]
  resource_group: production #only one deploy job at a time
  script:
    - echo "Publish local release $BUILD_VERSION"
    - |
      ./gradlew publish -PbuildVersion=$BUILD_VERSION \
      -PdoPublish=true \
      -PisRelease=false \
      -PlocalUrl=$LOCAL_REPO_URL \
      -PlocalRepoUser=$LOCAL_REPO_USERNAME \
      -PlocalRepoPassword=$LOCAL_REPO_PASSWORD
    - export NEW_BUILD_NUMBER=$((BUILD_NUMBER + 1))
    - echo "Update BUILD_NUMBER to $NEW_BUILD_NUMBER"
    - curl --request PUT --header "PRIVATE-TOKEN:$API_TOKEN" --form "value=$NEW_BUILD_NUMBER" "$GITLAB_API_URL/BUILD_NUMBER"
git-version-tag:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  stage: publish
  needs: [ deploy-job ]
  image:
    name: alpine/git:v2.49.1 #need git
    entrypoint: ["/bin/sh", "-c"]
  script:
    - echo "Setting tag v$RELEASE_VERSION on gitlab."
    - git status
    - git tag "v$RELEASE_VERSION"
    - git push origin "v$RELEASE_VERSION"


publish-job:
  allow_failure: false
  when: manual
  stage: publish
  only:
    - main
    - master
  needs: [ "test-job" ]
  resource_group: production #only one deploy job at a time
  script:
    - export NEW_BUILD_VERSION=$MAJOR.$MINOR.0
    - echo "Publish public release $NEW_BUILD_VERSION"^
    - mkdir -p "$CI_PROJECT_DIR/.ci-secrets"
    - printf '%s' "$GPG_SECRING" | base64 -d > "$CI_PROJECT_DIR/.ci-secrets/secring.gpg"
    - echo "New Build Version $NEW_BUILD_VERSION"
    - chmod 600 "$CI_PROJECT_DIR/.ci-secrets/secring.gpg"
    - |
      ./gradlew publishToSonatype closeSonatypeStagingRepository -PbuildVersion=$NEW_BUILD_VERSION \
      -PdoPublish=true \
      -PisRelease=true \
      -PsonatypeUsername=$PUBLIC_REPO_USERNAME \
      -PsonatypePassword=$PUBLIC_REPO_PASSWORD \
      -Psigning.keyId=$GPG_ID \
      -Psigning.password=$GPG_PASSWORD \
      -Psigning.secretKeyRingFile="$CI_PROJECT_DIR/.ci-secrets/secring.gpg"
    - export NEW_MINOR=$((MINOR + 1))
    - echo "Update MINOR to $NEW_MINOR, set BUILD_NUMBER to 0"
    - curl --request PUT --header "PRIVATE-TOKEN:$API_TOKEN" "$GITLAB_API_URL/MINOR" --form "value=$NEW_MINOR"
    - curl --request PUT --header "PRIVATE-TOKEN:$API_TOKEN" "$GITLAB_API_URL/BUILD_NUMBER" --form "value=0"
