stages: # List of stages for jobs, and their order of execution
  #- build
  - test
  - visualize
  - deploy


#build-job:       # This job runs in the build stage, which runs first.
#  stage: build
#  script:
#    - echo "Compiling the code..."
#    - echo "Compile complete."

unit-test-job: # This job runs in the test stage.
  stage: test
  # It only starts when the job in the build stage completes successfully.
  image: eclipse-temurin:21
  script:
    - ./gradlew test koverXmlReport koverLog
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml

    paths:
      - build/reports/kover/*
  coverage: "/application line coverage: ([0-9]+\\.?[0-9]*)%/"

coverage-test:
  stage: visualize
  script:
    - ./gradlew test koverXmlReport
  needs: [ "unit-test-job" ]
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/cobertura.xml

code-style:
  stage: test
  image: eclipse-temurin:21
  script:
    - ./gradlew detektGenerateConfig
    - ./gradlew detekt
