stages: # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:
  stage: build
  image: amazoncorretto:21
  script:
    - ./gradlew compileJava
  artifacts:
    when: always
    paths:
      - build/

unit-test-job:
  stage: test
  image: amazoncorretto:21
  needs: ["build-job"]
  script:
    - ./gradlew test koverXmlReport koverLog
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
      coverage_report:
        coverage_format: cobertura
        path: build/reports/kover/report.xml

    paths:
      - build/reports/kover/*
  coverage: "/application line coverage: ([0-9]+\\.?[0-9]*)%/"

code-style:
  stage: test
  needs: ["build-job"]
  image: amazoncorretto:21
  script:
    - ./gradlew detektGenerateConfig
    - ./gradlew detekt

deploy-job:
  stage: deploy
  only:
    - main
  needs: [ "build-job" ]
  image: amazoncorretto:21
  script:
    - ./gradlew publish -PbuildNumber=$CI_PIPELINE_IID \
      -DdoPublish=true \
      -DlocalUrl=$LOCAL_REPO_URL \
      -DlocalRepoUser=$LOCAL_REPO_USERNAME \
      -DlocalRepoPassword=$LOCAL_REPO_PASSWORD

# Keep for first public release of reengineered mobitopp
#public-deploy-job:
#  stage: deploy
#  only:
#    - main
#  when: manual
#  image: amazoncorretto:21
#  script:
#    - ./gradlew build publish -PbuildNumber=$CI_PIPELINE_IID \
#      -DdoPublish=true \
#      -DlocalUrl=$LOCAL_REPO_URL \
#      -DlocalRepoUser=$LOCAL_REPO_USERNAME \
#      -DlocalRepoPassword=$LOCAL_REPO_PASSWORD \
#      -DisRelease=true \
#      -DpublicUrl=$PUBLIC_REPO_URL \
#      -DpublicRepoUser=$PUBLIC_REPO_USERNAME \
#      -DpublicRepoPassword=$PUBLIC_REPO_PASSWOR
