package core.statemachine

import utils.units.AbsoluteTime

/**
 * Interface representing a state machine that processes [Event]s/[Message]s and manages state transitions.
 * State machines can be used to define dynamic agent behavior, controlling how agents respond to events.
 */
interface StateMachine {

    val name: String

    /**
     * Starts the state machine by entering its initial state.
     *
     * @return Events generated by entering the initial state
     */
    fun start(): Events

    /**
     * Processes an [Event] by updating the current time and handling the contained message.
     *
     * @param event The event to be processed
     * @return Events generated in response to processing the given event
     */
    fun process(event: Event<*>): Events {
        setTime(event.receiveTime)
        return process(event.content)
    }

    /**
     * Updates the current time of the state machine.
     *
     * @param time The new current time
     */
    fun setTime(time: AbsoluteTime)

    /**
     * Processes the given [message] and handle any resulting state transitions.
     *
     * @param message The message to process
     * @return Events generated as a result of processing the message and potential state transitions
     */
    fun process(message: Message): Events
}

/**
 * Type alias representing the result of processing a message in a state.
 * The pair consists of events generated and an optional next state to transition to.
 */
typealias StateTransition = Pair<Events, State?>

/**
 * Constant representing a null transition, where no events are generated and no state change occurs.
 */
val NULL_TRANSITION = (emptyList<Event<*>>() to null)

/**
 * Interface representing a named state in a state machine.
 * States define how agents respond to messages and when they should transition to other states.
 * The following behavior can be modeled:
 *  - behavior when entering the state
 *  - behavior in response to receiving a message (with potential transition to another state)
 *  - spontaneous transition behavior not triggered by a message but internal state variables
 *    (should be checked after each invocation of [enter] and [processMessage])
 */
interface State {

    val name: String
    val time: AbsoluteTime
    val agent: Agent<*>

    /**
     * Updates the current time of the state.
     *
     * @param time The new current time
     */
    fun updateTime(time: AbsoluteTime)

    /**
     * Called when the [StateMachine] enters this state.
     *
     * @return Events generated in response entering this state
     */
    fun enter(): Events

    /**
     * Processes a [Message] and determines if a state transition should occur.
     *
     * @param message The message to process
     * @return A [StateTransition] containing response [Event]s and a potential next [State].
     */
    fun processMessage(message: Message): StateTransition

    /**
     * Determines if a state transition should occur without receiving a message.
     * This is used for transitory states that immediately transition to another state without passing time.
     *
     * @return A [StateTransition] containing response [Event]s and a potential next [State].
     */
    fun fallbackTransition(): StateTransition

    /**
     * Called when the [StateMachine] is interrupted.
     *
     * @return Events generated by interrupting this state
     */
    fun interrupt(): Events
}

/**
 * Interface for creating state machines for specific agent types.
 *
 * @param A The type of agent this factory creates state machines for
 */
interface StateMachineFactory<A : Agent<out Message>> {
    /** name of the type of [StateMachine]s this factory creates */
    val name: String

    /**
     * Creates a state machine for an agent starting at a specific time.
     *
     * @param startTime The time at which the state machine should start
     * @param agent The agent for which to create the state machine
     * @return A new state machine for the agent
     */
    fun create(startTime: AbsoluteTime, agent: A): StateMachine = create(initialState(startTime, agent))

    /**
     * Creates a state machine with a specific initial state.
     *
     * @param initialState The initial state of the state machine
     * @return A new state machine starting in the specified state
     */
    fun create(initialState: State): StateMachine

    /**
     * Creates the initial state for an agent starting at a specific time.
     *
     * @param startTime The time at which the state should start
     * @param agent The agent for which to create the initial state
     * @return The initial state for the agent
     */
    fun initialState(startTime: AbsoluteTime, agent: A): State
}

/**
 * Implementation of [StateMachine] that handles transitory states.
 * Transitory states are states that immediately transition to another state without passing time / receiving a message.
 *
 * @property name The name of this state machine
 * @property initial The initial state of this state machine
 */
open class TransitoryStateMachine(override val name: String, initial: State) : StateMachine {

    /**
     * The current state of this state machine.
     */
    protected var currentState: State = initial
    // To avoid storing initial state, current state is initialized before start!!

    /**
     * Starts the state machine by transitioning iteratively the first non-transitory state starting from the initial state.
     *
     * @return Events generated by entering the initial state and any subsequent transitory states
     */
    override fun start(): Events = findNonTransitoryState(currentState)

    override fun setTime(time: AbsoluteTime) {
        currentState.updateTime(time)
    }

    /**
     * Processes a message by passing it to the current state and handling any resulting state transitions.
     * If the message triggers a state transition to a transitory state, iterates state transitions until
     * the first non-transitory state is found.
     *
     * @param message The message to process
     * @return Events generated as a result of processing the message
     */
    override fun process(message: Message): Events {
        val result: MutableList<Event<*>> = mutableListOf()

        val (responses, transitionTo) = currentState.processMessage(message)
        result += responses

        val nextState = transitionTo ?: run {
            val (messages, transitionElse) = currentState.fallbackTransition()
            result += messages
            transitionElse
        }

        nextState?.let { state ->
            result += findNonTransitoryState(state)
        }

        return result
    }

    /**
     * Finds the first non-transitory state starting from the given state.
     * A non-transitory state is one that does not immediately transition to another state.
     *
     * @param state The state to start from
     * @return Events generated by entering the given state and any subsequent transitory states
     */
    protected open fun findNonTransitoryState(state: State): Events {
        val result: MutableList<Event<*>> = mutableListOf()

        var nextState: State = state
        var nextTransition: State? = state
        while (nextTransition != null) {
            nextState = nextTransition
            result += nextState.enter()

            val (instantTransitionResponse, transitionElse) = nextState.fallbackTransition()
            result += instantTransitionResponse

            nextTransition = transitionElse
        }

        currentState = nextState

        return result
    }
}
