[versions]
kotlin = "2.2.0"
ksp = "2.2.0-2.0.2"
kotlinpoet = "2.2.0"
kotlin-compile-testing-ksp = "1.6.0"
detekt = "1.23.8"
junit = "5.13.2"
kover = "0.9.1"
kandy = "0.8.0"
shadowjar = "8.1.1"
# kotlinx libs
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
kotlinx-html = "0.12.0"
kotlin-statistics = "0.2.1"
# other libs
jackson-parser = "2.20.0"
jackson-dataformat-csv = "2.20.0"
jackson-kotlin-serialization = "2.20.0"
commons-compress = "1.28.0"
xz = "1.10"
progressbar = "0.10.1"
exp4j = "0.4.8"
fast-utils = "8.5.16"
# ifv units
ifv-units= "1.0.1"
ifv-visum-netparser = "0.11.2"
ifv-actitopp-NG = "0.10.4"
ifv-discrete-choice = "0.1.2"


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
shadowjar = { id = "com.github.johnrengelman.shadow", version.ref = "shadowjar"}


[libraries]
# ifv libs
ifv-units = { module = "edu.kit.ifv.mobitopp:kotlin-units", version.ref = "ifv-units" }
ifv-visum-netparser = { module = "edu.kit.ifv.mobitopp:visumnetfileparser", version.ref = "ifv-visum-netparser" }
ifv-actitoppNG = { module = "edu.kit.ifv.mobitopp:actitoppNG", version.ref = "ifv-actitopp-NG" }
ifv-discrete-choice = {module = "edu.kit.ifv.mobitopp:discrete-choice", version.ref = "ifv-discrete-choice"}

# testing libs
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
kotlin-compile-testing-ksp = { module = "com.github.tschuchortdev:kotlin-compile-testing-ksp", version.ref = "kotlin-compile-testing-ksp" }

# annotation processing libs
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoetksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }
symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

# kandy libs
kandy-lets-plot = { module = "org.jetbrains.kotlinx:kandy-lets-plot", version.ref = "kandy" }
kandy-util = { module = "org.jetbrains.kotlinx:kandy-util", version.ref = "kandy" }
kandy-api = { module = "org.jetbrains.kotlinx:kandy-api", version.ref = "kandy" }

# detekt libs
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-cli = { module = "io.gitlab.arturbosch.detekt:detekt-cli", version.ref = "detekt" }
detekt-api = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt" }
detekt-rules = { module = "io.gitlab.arturbosch.detekt:detekt-rules", version.ref = "detekt" }


# kotlinx libs
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-statistics = { module = "org.jetbrains.kotlinx:kotlin-statistics-jvm", version.ref = "kotlin-statistics" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "kotlinx-serialization" }
kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version.ref = "kotlinx-html" }

# other libs
jackson-parser = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson-parser" }
jackson-dataformat-csv = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-csv", version.ref = "jackson-dataformat-csv" }
jackson-kotlin-serialization = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson-kotlin-serialization" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }
xz = { module = "org.tukaani:xz", version.ref = "xz" }
progressbar = { module = "me.tongfei:progressbar", version.ref = "progressbar" }
exp4j = { module = "net.objecthunter:exp4j", version.ref = "exp4j" }
fast-util = { module = "it.unimi.dsi:fastutil", version.ref = "fast-utils"}
