package core.statemachine.builder

import core.statemachine.Agent
import core.statemachine.Message
import core.statemachine.State
import core.statemachine.StateMachine
import core.statemachine.StateMachineFactory
import core.statemachine.TransitoryStateMachine
import utils.units.AbsoluteTime

/**
 * Implementation of [StateMachineFactory] that caches state behaviors.
 * This class is responsible for creating state machines and resolving state data to actual state instances.
 *
 * @param A The type of agent this factory creates state machines for
 * @property builders The list of state builders for all states in this state machine
 * @property initialize Function to initialize the start state data for an agent at a specific time
 * @property name The name of the state machine
 */
internal class CachedBehaviorStateMachineFactory<A : Agent<out Message>>(
    builders: List<StateBuilder<out StateData>>,
    val initialize: (AbsoluteTime, A) -> StateData,
    override val name: String,
) : StateResolver,
    StateMachineFactory<A> {

    /**
     * Map of state types to their behaviors.
     * This is used to cache state behaviors so they don't need to be rebuilt for each state instance.
     */
    private val states: Map<AnyStateType, StateBehavior<out StateData>> = builders.associate {
        it.type to it.build(this)
    }

    /**
     * Resolves state data to an actual state instance.
     * This is used during the state machine execution to create state instances from state data.
     *
     * @param D The type of state data to resolve
     * @param stateData The state data to resolve
     * @return The resolved state
     * @throws IllegalArgumentException if no state definition is found for the given state data
     */
    @Suppress("UNCHECKED_CAST")
    override fun <D> resolve(stateData: D): State where D : StateData {
        val stateType = stateData::class
        return requireNotNull(states[stateType]) {
            "No state definition found for state data: $stateData"
        }.let {
            it as? StateBehavior<D>
        }?.let {
            StateImpl<D>(stateData, it)
        }!!
    }

    override fun create(initialState: State): StateMachine = TransitoryStateMachine(
        name = name,
        initial = initialState,
    )

    override fun initialState(startTime: AbsoluteTime, agent: A): State = resolve(initialize(startTime, agent))
}

/**
 * Implementation of State that delegates to a StateBehavior.
 * This class combines state data with a state behavior to create a complete state.
 *
 * @param D The type of state data this state uses
 * @property data The state data for this state
 * @property behavior The behavior for this state
 */
private data class StateImpl<D : StateData>(private val data: D, private val behavior: StateBehavior<D>) : State {

    override val name = data::class.simpleName!!
    override val time: AbsoluteTime get() = data.time
    override val agent: Agent<*> get() = data.agent

    override fun updateTime(time: AbsoluteTime) = data.updateTime(time)

    /**
     * Called when the state machine enters this state.
     * Delegates to the state behavior's enter method.
     *
     * @return Events generated by entering this state
     */
    override fun enter() = behavior.enter(data)

    /**
     * Processes a message and determines if a state transition should occur.
     * Delegates to the state behavior's processMessage method.
     *
     * @param message The message to process
     * @return A pair containing events generated and an optional next state to transition to
     */
    override fun processMessage(message: Message) = behavior.processMessage(data, message)

    /**
     * Determines if a state transition should occur without receiving a message.
     * Delegates to the state behavior's fallbackTransition method.
     *
     * @return A pair containing events generated and an optional next state to transition to
     */
    override fun fallbackTransition() = behavior.fallbackTransition(data)

    /**
     * Called when the state machine is interrupted.
     * Delegates to the state behavior's interrupt method.
     *
     * @return Events generated by interrupting this state
     */
    override fun interrupt() = behavior.interrupt(data)

    override fun toString() = "[${data.time}] " + data::class.simpleName!! + "($data)"
}
