package core.statemachine.builder

import core.statemachine.Agent
import core.statemachine.Events
import core.statemachine.Message
import core.statemachine.State
import utils.units.AbsoluteTime
import kotlin.reflect.KClass

/**
 * Type alias for a Kotlin class representing any type of state.
 * Used when the specific state data type is not important.
 */
typealias AnyStateType = KClass<out StateData>

/**
 * Type alias for a Kotlin class representing a specific state data type.
 * Used for type-safe state data handling in the state machine.
 *
 * @param D The specific state data type
 */
typealias StateType<D> = KClass<out D>

/**
 * Interface representing the data associated with a state in a state machine.
 * State data contains at least the current time and agent, and can be updated as the state machine runs.
 * This separates state variables which are different for each agent,
 * from [StateBehavior] which describes the behavior functions which can be reused.
 */
interface StateData {
    /**
     * The current time in the state.
     */
    val time: AbsoluteTime

    /**
     * The agent associated with this state data.
     */
    val agent: Agent<*>

    /**
     * Updates the current time of the state data.
     *
     * @param time The new current time
     */
    fun updateTime(time: AbsoluteTime)
}

/**
 * Base implementation of [StateData] that provides time management.
 * This class can be extended to create specific state data types.
 *
 * @property time The initial time for this state data
 */
abstract class BaseStateData(time: AbsoluteTime) : StateData {

    final override var time: AbsoluteTime = time
        private set

    override fun updateTime(time: AbsoluteTime) {
        // TODO require time only increases?
        this.time = time
    }
}

/**
 * Interface representing the behavior of a state in a state machine.
 * State behaviors define how states respond to messages and when they should transition to other states.
 * Each state behavior function receives a [StateData] object as input.
 * This separates [StateData] variables which are different for each agent,
 * from behavior function which can be reused.
 *
 * @param D The type of state data this behavior works with
 */
interface StateBehavior<D : StateData> {
    /**
     * Called when the [StateData] enters the given state.
     *
     * @param data The state data for this state
     * @return Events generated by entering this state
     */
    fun enter(data: D): Events

    /**
     * Processes a message and determines if a state transition should occur.
     *
     * @param data The state data for this state
     * @param message The message to process
     * @return A pair containing events generated and an optional next state to transition to
     */
    fun processMessage(data: D, message: Message): Pair<Events, State?>

    /**
     * Determines if a state transition should occur without receiving a message.
     * This is used for transitory states that immediately transition to another state.
     *
     * @param data The state data for this state
     * @return A pair containing events generated and an optional next state to transition to
     */
    fun fallbackTransition(data: D): Pair<Events, State?>

    /**
     * Called when the state machine is interrupted.
     *
     * @param data The state data for this state
     * @return Events generated by interrupting this state
     */
    fun interrupt(data: D): Events
}
