package edu.kit.ifv.utils.collections
/**
 * Generates a sequence of all permutations of the underlying Iterables.
 *
 * Taken from Reddit (https://www.reddit.com/r/Kotlin/comments/isg16h/what_is_the_fastest_way_combination_in_kotlin/)
 */
@Suppress("CognitiveComplexMethod")
fun <T> Iterable<T>.permutations(length: Int? = null): Sequence<List<T>> = sequence {
    val pool = this@permutations as? List<T> ?: toList()
    val n = pool.size
    val r = length ?: n
    if (r > n) return@sequence
    val indices = IntArray(n) { it }
    val cycles = IntArray(r) { n - it }
    yield(List(r) { pool[indices[it]] })
    if (n == 0) return@sequence
    cyc@ while (true) {
        for (i in r - 1 downTo 0) {
            cycles[i]--
            if (cycles[i] == 0) {
                val temp = indices[i]
                for (j in i..<n - 1) indices[j] = indices[j + 1]
                indices[n - 1] = temp
                cycles[i] = n - i
            } else {
                val j = n - cycles[i]
                indices[i] = indices[j].also { indices[j] = indices[i] }
                yield(List(r) { pool[indices[it]] })
                continue@cyc
            }
        }
        return@sequence
    }
}

/**
 * Generates all the ordered pairings by permuting the original iterable and generating all ordered pairings for each
 * permutation.
 */
fun <T> Iterable<Pair<T, T>>.orderedPermutations(): Sequence<List<T>> = permutations().flatMap { it.orderedPairings() }

/**
 * Maps the elements of the pair iterable based on the indices permutations generated by [generatePairings]. Since this
 * method steps through the list the first element will always match to the index 0
 */
fun <T> Iterable<Pair<T, T>>.orderedPairings(): Sequence<List<T>> {
    val pool = this as? List<Pair<T, T>> ?: toList()
    val result = pool.flatMap { (f, s) -> listOf(f, s) }
    return generatePairings(IntArray(2 * pool.size) { it }, 0).map { indices ->
        result.zip(indices).sortedBy { it.second }.map { it.first }
    }
}

/**
 * This method generates a sequence of all possible indices pairings for a given item array. Originally C++ code
 * Adapted from [StackOverflow](https://stackoverflow.com/questions/37447697/an-efficient-method-to-generate-all-possible-ways-to-pair-up-items-in-a-data-set)
 */
fun generatePairings(items: IntArray, start: Int, itemcount: Int = items.size): Sequence<List<Int>> {
    if (items.size % 2 != 0) {
        return emptySequence() // must be an even number of items
    }

    // Is this a complete pairing?
    return if (start == itemcount) {
        val res = items.toMutableList()
        for (i in 0..<res.size / 2) {
            // This swap is necessary because the original algorithm does not maintain ordering, only matching
            if (res[2 * i] > res[2 * i + 1]) {
                res[2 * i] = res[2 * i + 1].also { res[2 * i + 1] = res[2 * i] }
            }
        }

        listOf(res).asSequence()
    } else {
        // For the next pair, choose the first element in the list for the
        // first item in the pair (meaning we don't have to do anything
        // but leave it in place), and each of the remaining elements for
        // the second item.
        sequence {
            var j = start + 1
            while (j < itemcount) {
                // Swap start+1 and j

                val temp = items[start + 1]
                items[start + 1] = items[j]
                items[j] = temp

                // Recurse
                yieldAll(generatePairings(items, start + 2, itemcount))

                // Swap them back
                items[j] = items[start + 1]
                items[start + 1] = temp
                j++
            }
        }
    }
}

fun Int.toBinaryRepresentation(size: Int): List<Boolean> = Integer.toBinaryString(this).padStart(size, '0').map {
    it == '1'
}

fun <T> Collection<T>.subsets(): List<Set<T>> = (0..<(1 shl size)).map { num ->
    num.toBinaryRepresentation(size).zip(this).filter { it.first }.map { it.second }.toSet()
}

fun <S, T> Collection<S>.cartesianProduct(other: Collection<T>): List<Pair<S, T>> = flatMap { a ->
    other.map { b ->
        a to b
    }
}

fun <S, T, O> Collection<S>.cartesianProduct(other: Collection<T>, third: Collection<O>): List<Triple<S, T, O>> =
    flatMap { a ->
        other.flatMap { b ->
            third.map { c ->
                Triple(a, b, c)
            }
        }
    }
