package edu.kit.ifv.domain.synthesis.behavior.cars.choicemodels.parameters
@Suppress(
    "MagicNumber",
    "ConstructorParameterNaming",
) // Parameters for configurations are magic, but there is no better representation
data class EngineParameters(
    val CONST_BEV: Double = -2.3079 - 7.5,
    val WORKDIS_BEV: Double = 0.0525,
    val AUSBDIS_BEV: Double = 0.0249,
    val SEX_MALE_BEV: Double = -0.0310,
    val JOB_FULLTIME_BEV: Double = 0.2378,
    val JOB_PARTTIME_BEV: Double = -0.0814,
    val JOBLESS_BEV: Double = -0.0755,
    val STUDENT_TERTIARY_BEV: Double = -1.0111,
    val STUDENT_SECONDARY_BEV: Double = 0.0151,
    val EDUCATION_BEV: Double = -0.1837,
    val UNEMPLOYED_BEV: Double = -0.1599,
    val RETIRED_BEV: Double = -0.2180,
    val AGE_18_TO_25_BEV: Double = -0.1250,
    val AGE_25_TO_35_BEV: Double = 0.2121,
    val AGE_35_TO_45_BEV: Double = 0.3012,
    val AGE_45_TO_55_BEV: Double = 0.3612,
    val AGE_55_TO_65_BEV: Double = 0.3242,
    val AGE_65_TO_75_BEV: Double = 0.3948,
    val AGE_75_TO_85_BEV: Double = -0.3124,
    val ANZ_PKW_1_BEV: Double = 0.8749,
    val ANZ_PKW_2_BEV: Double = 0.6476,
    val ANZ_PKW_3_BEV: Double = 0.8238,
    val ANZ_PKW_4_BEV: Double = 0.7095,
    val HHGRO_1_BEV: Double = 0.2985,
    val HHGRO_2_BEV: Double = -0.1356,
    val HHGRO_3_BEV: Double = -0.4157,
    val HHGRO_4_BEV: Double = -0.1025,
    val STADT_BEV: Double = -3 - 6.5,
    val KLEINSTADT_BEV: Double = -1.0 - 2.0,
    val STADTRAUM_BEV: Double = 0.1 - 0.8,
    val LANDRAUM_BEV: Double = 0.0,
    val CONST_EREV: Double = -2.3079 - 8,
    val WORKDIS_EREV: Double = 0.0525,
    val AUSBDIS_EREV: Double = 0.0249,
    val SEX_MALE_EREV: Double = -0.0310,
    val JOB_FULLTIME_EREV: Double = 0.2378,
    val JOB_PARTTIME_EREV: Double = -0.0814,
    val JOBLESS_EREV: Double = -0.0755,
    val STUDENT_TERTIARY_EREV: Double = -1.0111,
    val STUDENT_SECONDARY_EREV: Double = 0.0151,
    val EDUCATION_EREV: Double = -0.1837,
    val UNEMPLOYED_EREV: Double = -0.1599,
    val RETIRED_EREV: Double = -0.2180,
    val AGE_18_TO_25_EREV: Double = -0.1250,
    val AGE_25_TO_35_EREV: Double = 0.2121,
    val AGE_35_TO_45_EREV: Double = 0.3012,
    val AGE_45_TO_55_EREV: Double = 0.3612,
    val AGE_55_TO_65_EREV: Double = 0.3242,
    val AGE_65_TO_75_EREV: Double = 0.3948,
    val AGE_75_TO_85_EREV: Double = -0.3124,
    val ANZ_PKW_1_EREV: Double = 0.8749,
    val ANZ_PKW_2_EREV: Double = 0.6476,
    val ANZ_PKW_3_EREV: Double = 0.8238,
    val ANZ_PKW_4_EREV: Double = 0.7095,
    val HHGRO_1_EREV: Double = 0.2985,
    val HHGRO_2_EREV: Double = -0.1356,
    val HHGRO_3_EREV: Double = -0.4157,
    val HHGRO_4_EREV: Double = -0.1025,
    val STADT_EREV: Double = -3 - 6.5,
    val KLEINSTADT_EREV: Double = -1.0 - 2.0,
    val STADTRAUM_EREV: Double = 0.1 - 0.8,
    val LANDRAUM_EREV: Double = 0.0,
) {
    fun electicParameters(): EngineSpecificParameters = EngineSpecificParameters(
        CONST_BEV,
        WORKDIS_BEV,
        AUSBDIS_BEV,
        SEX_MALE_BEV,
        JOB_FULLTIME_BEV,
        JOB_PARTTIME_BEV,
        JOBLESS_BEV,
        STUDENT_TERTIARY_BEV,
        STUDENT_SECONDARY_BEV,
        EDUCATION_BEV,
        UNEMPLOYED_BEV,
        RETIRED_BEV,
        AGE_18_TO_25_BEV,
        AGE_25_TO_35_BEV,
        AGE_35_TO_45_BEV,
        AGE_45_TO_55_BEV,
        AGE_55_TO_65_BEV,
        AGE_65_TO_75_BEV,
        AGE_75_TO_85_BEV,
        ANZ_PKW_1_BEV,
        ANZ_PKW_2_BEV,
        ANZ_PKW_3_BEV,
        ANZ_PKW_4_BEV,
        HHGRO_1_BEV,
        HHGRO_2_BEV,
        HHGRO_3_BEV,
        HHGRO_4_BEV,
        STADT_BEV,
        KLEINSTADT_BEV,
        STADTRAUM_BEV,
        LANDRAUM_BEV,
    )

    fun hybridParameters(): EngineSpecificParameters = EngineSpecificParameters(
        CONST_EREV,
        WORKDIS_EREV,
        AUSBDIS_EREV,
        SEX_MALE_EREV,
        JOB_FULLTIME_EREV,
        JOB_PARTTIME_EREV,
        JOBLESS_EREV,
        STUDENT_TERTIARY_EREV,
        STUDENT_SECONDARY_EREV,
        EDUCATION_EREV,
        UNEMPLOYED_EREV,
        RETIRED_EREV,
        AGE_18_TO_25_EREV,
        AGE_25_TO_35_EREV,
        AGE_35_TO_45_EREV,
        AGE_45_TO_55_EREV,
        AGE_55_TO_65_EREV,
        AGE_65_TO_75_EREV,
        AGE_75_TO_85_EREV,
        ANZ_PKW_1_EREV,
        ANZ_PKW_2_EREV,
        ANZ_PKW_3_EREV,
        ANZ_PKW_4_EREV,
        HHGRO_1_EREV,
        HHGRO_2_EREV,
        HHGRO_3_EREV,
        HHGRO_4_EREV,
        STADT_EREV,
        KLEINSTADT_EREV,
        STADTRAUM_EREV,
        LANDRAUM_EREV,
    )
}
