package core.statemachine.builder.states

import core.statemachine.Events
import core.statemachine.Message
import core.statemachine.NULL_TRANSITION
import core.statemachine.StateTransition
import core.statemachine.builder.AnyStateType
import core.statemachine.builder.OnEnter
import core.statemachine.builder.StateBehavior
import core.statemachine.builder.StateBuilder
import core.statemachine.builder.StateData
import core.statemachine.builder.StateResolver
import core.statemachine.sendScope

/**
 * Implementation of [StateBuilder] for final states.
 * Final states do not transition to other states and represent the end of a state machine.
 *
 * @param D The type of state data this builder works with
 * @property type The type of state this builder creates
 * @property onEnterScope Function to execute when entering this state
 */
internal class FinalStateBuilder<D>(override val type: AnyStateType, private val onEnterScope: OnEnter<D>) :
    StateBuilder<D> where D : StateData {

    /**
     * Builds a final state behavior with this builders [onEnterScope].
     *
     * @param resolver The resolver used to resolve state references
     * @return A state behavior for final states
     */
    override fun build(resolver: StateResolver): StateBehavior<D> = FinalStateBehavior(onEnterScope)
}

/**
 * Implementation of [StateBehavior] for final states.
 * Final states do not transition to other states and represent the end of a state machine.
 *
 * @param D The type of state data this behavior works with
 * @property onEnterScope Function to execute when entering this state
 */
private class FinalStateBehavior<D>(private val onEnterScope: OnEnter<D>) : StateBehavior<D> where D : StateData {

    /**
     * Called when the state machine enters this state.
     * Executes the [onEnterScope] function and collects any events generated.
     *
     * @param data The state data for this state
     * @return Events generated by entering this state
     */
    override fun enter(data: D): Events = sendScope(data) { send ->
        data.onEnterScope(send)
    }.first

    /**
     * Processes a message and determines if a state transition should occur.
     * This method is not supported for final states, as they do not process messages.
     *
     * @param data The state data for this state
     * @param message The message to process
     * @return This method always throws an exception
     * @throws UnsupportedOperationException always, as final states do not process messages
     */
    override fun processMessage(data: D, message: Message): StateTransition =
        throw UnsupportedOperationException("processMessage should not be called on FinalStates")

    /**
     * Determines if a state transition should occur without receiving a message.
     * For final states, this always returns NULL_TRANSITION, as they do not transition to other states.
     *
     * @param data The state data for this state
     * @return A pair containing no events and no next state
     */
    override fun fallbackTransition(data: D): StateTransition = NULL_TRANSITION

    /**
     * Called when the state machine is interrupted.
     * This method is not implemented for final states.
     *
     * @param data The state data for this state
     * @return This method always throws an exception
     * @throws UnsupportedOperationException always, as interrupt is not implemented for final states
     */
    override fun interrupt(data: D): Events =
        throw UnsupportedOperationException("interrupt should not be called on FinalStates")
}
