package core.statemachine.builder.states

import core.statemachine.Events
import core.statemachine.Message
import core.statemachine.StateTransition
import core.statemachine.builder.AnyStateType
import core.statemachine.builder.MandatoryTransitionBuilder
import core.statemachine.builder.OnEnter
import core.statemachine.builder.StateBehavior
import core.statemachine.builder.StateBuilder
import core.statemachine.builder.StateData
import core.statemachine.builder.StateResolver
import core.statemachine.builder.TransitionToNext
import core.statemachine.sendScope

/**
 * Implementation of [StateBuilder] and [MandatoryTransitionBuilder] for transitory states.
 * Transitory states immediately transition to another state without receiving a message or passing time in the state.
 *
 * @param D The type of state data this builder works with
 * @property type The type of state this builder creates
 * @property onEnter Function to execute when entering this state
 */
internal class TransitoryStateBuilder<D>(override val type: AnyStateType, private val onEnter: OnEnter<D>) :
    StateBuilder<D>,
    MandatoryTransitionBuilder<D> where D : StateData {

    /**
     * Function to determine the next state for this transitory state.
     */
    private lateinit var nextTransition: TransitionToNext<D>

    /**
     * Defines the next state for this transitory state.
     *
     * @param onTransition Function that returns the next state data
     */
    override fun next(onTransition: TransitionToNext<D>) {
        nextTransition = onTransition
    }

    /**
     * Builds a transitory state behavior using the provided state resolver.
     *
     * @param resolver The resolver used to resolve state references
     * @return A state behavior for transitory states
     */
    override fun build(resolver: StateResolver): StateBehavior<D> = TransitoryStateBehavior(
        onEnterScope = onEnter,
        nextStateTransition = if (::nextTransition.isInitialized) {
            nextTransition
        } else {
            error(
                "No next state was defined for transitory state '${type.simpleName}'!\n" +
                    "Use:\n" +
                    "  transState(${type.simpleName}::class) {\n" +
                    "      send -> /*init block if necessary*/\n" +
                    "  }.next {\n" +
                    "      NEXT STATE HERE\n" +
                    "  }\n" +
                    "to define the next state following this transitory state!",
            )
        },
        stateResolver = resolver,
    )
}

/**
 * Implementation of [StateBehavior] for transitory states.
 * Transitory states immediately transition to another state without receiving a message or passing time in the state.
 *
 * @param D The type of state data this behavior works with
 * @property onEnterScope Function to execute when entering this state
 * @property nextStateTransition Function to determine the next state for this transitory state
 * @property stateResolver Resolver used to resolve state references
 */
private class TransitoryStateBehavior<D>(
    private val onEnterScope: OnEnter<D>,
    private val nextStateTransition: TransitionToNext<D>,
    private val stateResolver: StateResolver,
) : StateBehavior<D> where D : StateData {

    /**
     * Called when the state machine enters this state.
     * Executes the onEnterScope function and collects any events generated.
     *
     * @param data The state data for this state
     * @return Events generated by entering this state
     */
    override fun enter(data: D): Events = sendScope(data) { send ->
        data.onEnterScope(send)
    }.first

    /**
     * Processes a message and determines if a state transition should occur.
     * This method is not supported for transitory states, as they automatically transition without receiving messages.
     *
     * @param data The state data for this state
     * @param message The message to process
     * @return This method always throws an exception
     * @throws UnsupportedOperationException always, as transitory states do not process messages
     */
    override fun processMessage(data: D, message: Message): StateTransition =
        throw UnsupportedOperationException("processMessage should not be called on TransitoryState")

    /**
     * Determines the next state for this transitory state.
     * This method is called automatically after entering a transitory state.
     *
     * @param data The state data for this state
     * @return A pair containing events generated and the next state to transition to
     */
    override fun fallbackTransition(data: D): StateTransition = sendScope(data) { send ->
        val nextState = data.nextStateTransition(send)
        stateResolver.resolve(nextState)
    }

    /**
     * Called when the state machine is interrupted.
     * This method is not implemented for transitory states.
     *
     * @param data The state data for this state
     * @return This method always throws an exception
     * @throws UnsupportedOperationException always, as interrupt is not implemented for transitory states
     */
    override fun interrupt(data: D): Events =
        throw UnsupportedOperationException("interrupt should not be called on TransitoryState")
}
