package usecases.steps.legacyData

import domain.data.DefaultHousehold
import domain.data.EconomicStatus
import domain.data.HouseholdBuilder
import domain.data.HouseholdId
import domain.data.LegacyZone
import domain.location.RoadPosition
import domain.location.RoadPositionInZone
import domain.location.parseRoadPosition
import modeling.steps.AddCsvStep
import modeling.steps.BuildStep
import modeling.steps.Context
import modeling.steps.CsvResource
import modeling.steps.FilterStep
import modeling.steps.ModelExecution
import units.CurrencyUnit
import usecases.steps.HouseholdContext
import usecases.steps.LegacyZonesContext
import utils.CodePlan
import utils.ErrorHandling
import utils.csv.CsvParser
import utils.csv.Row
import utils.csv.SEMICOLON
import utils.csv.currency
import utils.csv.decode
import utils.csv.int
import utils.csv.long
import utils.csv.withFilter
import java.io.File
import kotlin.random.Random

@Suppress("LongParameterList")
fun <S, C> S.prepareHouseholds(
    file: File? = null,
    delimiter: String = SEMICOLON,
    errorHandling: ErrorHandling = ErrorHandling.WARNING,
    columnTranslator: HouseholdColumns = HouseholdColumns(),
    roadPositionParser: (String) -> RoadPosition = String::parseRoadPosition,
    incomeUnit: CurrencyUnit? = null,
    economicalStatusCodes: CodePlan<EconomicStatus>? = null,
    filter: HouseholdColumns.(Row) -> Boolean = { true }
) where S : ModelExecution<C>, C : Context, C : LegacyZonesContext, C : HouseholdContext {
    val currencyUnit = incomeUnit ?: this.context.costUnit
    val zoneIndex = { context.zoneColumnIndex }
    val economicalStatusCodePlan = economicalStatusCodes ?: context.economicalStatusCodes

    val parser = CsvParser(errorHandling) { row ->
        /*Robin: The builder lambda expression is really difficult to handle, as it is autogenerated and the signature
        of the constructor does not necessarily match the interface construction. In this example I wrote a "Default"
        class which implements the logic of actually maintaining persons and cars, and thus does not require these sets
        from the constructor. The Annotation processing does not know that this implementation exists. I think the
        best approach would be to annotate classes only.
         */
        HouseholdBuilder { p0, p1, p2, p3, p4, p5, p6, p7, _, _, p10 ->
            DefaultHousehold(
                p0,
                p1,
                p2,
                p3,
                p4,
                p5,
                p6,
                p7,
                p10
            )
        }.apply {
            householdNumber = row.long(columnTranslator.hhNumberColumn)
            surveyYear = row.int(columnTranslator.yearColumn)
            // Robin: I converted this builder call to the location as found in [Household]
            location = RoadPositionInZone(
                row(columnTranslator.locationColumn, roadPositionParser),
                getLegacyZone(zoneIndex, row.int(columnTranslator.zoneColumn))
            )
            // legacy household.csv files reference column instead of visum id
            domCode = row.int(columnTranslator.domCodeColumn)
            type = row.int(columnTranslator.typeColumn)
            incomePerMonth = row.currency(columnTranslator.incomeColumn, currencyUnit)
            economicStatus = row.decode(columnTranslator.economicalStatusColumn, economicalStatusCodePlan)
            id = HouseholdId(row.long(columnTranslator.hhIdColumn))
            // TODO this may be not the best random instantiation
            random = Random(row.long(columnTranslator.hhNumberColumn))
        }
    }
    val filterWrap: (Row) -> Boolean = { columnTranslator.filter(it) }

    this.prepareHouseholdsFile(parser.withFilter(filterWrap), file, delimiter)
}

/**
 * ROBIN: I think extracting a parameter object may be helpful to avoid the long parameter list, and makes the method
 * significantly more readable.
 */
data class HouseholdColumns(
    val hhNumberColumn: String = "householdNumber",
    val hhIdColumn: String = "householdId",
    val yearColumn: String = "year",
    val zoneColumn: String = "homeZone",
    val locationColumn: String = "homeLocation",
    val domCodeColumn: String = "domCode",
    val typeColumn: String = "type",
    val incomeColumn: String = "income",
    val economicalStatusColumn: String = "economicalStatus",
)
private fun getLegacyZone(
    zoneIndex: () -> Map<Int, LegacyZone>,
    matrixColumn: Int
) = requireNotNull(
    zoneIndex()[matrixColumn]
) {
    "Could not find zone with matrix column $matrixColumn " +
        "in index: ${zoneIndex()}"
}

fun <S, C> S.prepareHouseholdsFile(
    parser: CsvParser<HouseholdBuilder>,
    file: File? = null,
    delimiter: String = SEMICOLON,
) where S : ModelExecution<C>, C : Context, C : LegacyZonesContext, C : HouseholdContext {
    val path = this.context.demandFolder.path + "\\demand-data\\household.csv"
    val householdFile = file ?: File(path)

    val resource = CsvResource(householdFile, parser, delimiter)

    this.addStep(
        AddCsvStep(
            name = "load household csv",
            csv = resource,
            repository = context.householdRepository
        )
    )
}

fun <S, C> S.finishHouseholds() where S : ModelExecution<C>, C : HouseholdContext {
    this.addStep(BuildStep("finish households", context.householdRepository))
}

fun <S, C> S.filterHouseholds(valid: Collection<HouseholdId>) where S : ModelExecution<C>, C : HouseholdContext {
    this.addStep(
        FilterStep("filter households", context.householdRepository) {
            it.id in valid
        }
    )
}

fun <S, C> S.loadHouseholds(
    file: File? = null,
    errorHandling: ErrorHandling = ErrorHandling.WARNING,
    filter: HouseholdColumns.(Row) -> Boolean = {
        true
    }
) where S : ModelExecution<C>, C : Context, C : LegacyZonesContext, C : HouseholdContext {
    this.prepareHouseholds(file = file, errorHandling = errorHandling, filter = filter)
    this.finishHouseholds()
}
