package domain.synthesis.behavior.cars.choicemodels.parameters

data class EngineSpecificParameters(
    val constant: Double,
    val workDistance: Double,
    val educationDistance: Double,
    val isMale: Double,
    val fullTime: Double,
    val partTime: Double,
    val homekeeper: Double,
    val studentTertiary: Double,
    val studentSecondary: Double,
    val educationEmployment: Double,
    val unemployed: Double,
    val retired: Double,
    val age18to25: Double, // 18..25
    val age25to35: Double,
    val age35to45: Double,
    val age45to55: Double,
    val age55to65: Double,
    val age65to75: Double,
    val age75to85: Double,
    val numPKW1: Double,
    val numPKW2: Double,
    val numPKW3: Double,
    val numPKW4: Double,
    val householdSize1: Double,
    val householdSize2: Double,
    val householdSize3: Double,
    val householdSize4: Double,
    val regionStadt: Double,
    val regionKleinstadt: Double,
    val regionStadtraum: Double,
    val regionLandraum: Double,

)
