package domain.synthesis.behavior.cars.choicemodels.parameters

data class SimplifiedParameters(
    val constant: Double,
    val commuterDistance0to10kilometers: Double,
    val commuterDistance10to20kilometers: Double,
    val commuterDistance20to30kilometers: Double,
    val commuterDistance30to40kilometers: Double,
    val commuterDistance40to50kilometers: Double,
    val commuterDistanceAtLeast50kilometers: Double,
    val householdSize1: Double,
    val householdSize2: Double,
    val householdSize3orMore: Double,
    val incomeIn0to499: Double,
    val incomeIn500to999: Double,
    val incomeIn1000to1499: Double,
    val incomeIn1500to1999: Double,
    val incomeIn2000to2499: Double,
    val incomeIn2500to2999: Double,
    val incomeIn3000to3499: Double,
    val incomeAtLeast3500: Double,
    val incomeNegative: Double,
    val atLeast2Cars: Double,
    val female: Double,
)