package domain.jackson

import com.fasterxml.jackson.core.JsonGenerator
import com.fasterxml.jackson.core.JsonParser
import com.fasterxml.jackson.databind.DeserializationContext
import com.fasterxml.jackson.databind.JsonDeserializer
import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.JsonSerializer
import com.fasterxml.jackson.databind.SerializerProvider
import com.fasterxml.jackson.databind.module.SimpleModule
import java.util.ServiceLoader
import kotlin.collections.component1
import kotlin.collections.component2
import kotlin.collections.forEach

/**
 * Subprojects need to implement this interface and register it in the `META-INF` directory, if they want to add mappings
 * to __existing__ KeyValueSerializers/Deserializers.
 */
interface Repo<T> {
    val name: String
    val wraps: Class<T>
    fun getParameterSets(): Map<String, T>
}

/**
 * A builder for GenericKeyValueSerializers and Deserializers.
 * Collects all `Repo<T>` implementations from subprojects through the ServiceLoader
 * API (only if they are declared in the `META-INF` directory).
 *
 * @param default default mappings from strings to their appropriate translation.
 * @param wraps parameter to declare which class this Deserializer wraps. Needed for the collection of Repo<T>
 *     instances.
 */
class GenericKeyValueBuilder<T>(
    val wraps: Class<T>,
    val default: Map<String, T> = emptyMap(),
    val loadFromSubmodules: Boolean
) {

    val serializerMapping: Map<T, String> by lazy {
        deserializerMapping.reverseMapping()
    }

    val deserializerMapping: Map<String, T> by lazy {
        collectMappings(wraps, default, loadFromSubmodules)
    }

    fun getSerializer(): GenericKeyValueSerializer<T> {
        return GenericKeyValueSerializer(
            wraps,
            serializerMapping,
            false
        )
    }

    fun getDeserializer(): GenericKeyValueDeserializer<T> {
        return GenericKeyValueDeserializer(
            wraps,
            deserializerMapping,
            false
        )
    }

    /**
     * Creates a module containing both the serializer and deserializer that are generated by this class.
     */
    fun getModule(): SimpleModule {
        return SimpleModule("KeyValueSerializer of $wraps").run {
            addSerializer(wraps, getSerializer())
            addDeserializer(wraps, getDeserializer())
        }
    }
}

/**
 * Provides a simple deserializing from string to instance.
 * Collects all mappings from strings to T from subprojects through the ServiceLoader
 * API. (Collects all Repo<T> instances that are declared in a subproject).
 *
 * @param default default mappings from strings to their appropriate translation.
 * @param wraps parameter to declare which class this Deserializer wraps. Needed for the collection of Repo<T>
 *     instances.
 */
class GenericKeyValueDeserializer<T>(
    val wraps: Class<T>,
    val default: Map<String, T> = emptyMap(),
    val loadFromSubmodules: Boolean
) : JsonDeserializer<T>() {

    val mapping: Map<String, T> by lazy {
        collectMappings(wraps, default, loadFromSubmodules)
    }

    override fun deserialize(
        p: JsonParser,
        ctxt: DeserializationContext?
    ): T {
        val node = p.codec.readTree<JsonNode>(p)

        val type = when {
            node.isTextual -> node.asText()
            else -> node.get("type").asText()
        }
        return mapping[type] ?: error("Unknown type: $type. Can't deserialize $type. " +
            "Known types: ${mapping.keys}")
    }
}

/**
 * Provides a simple serializing from instance to string.
 * Collects all mappings from string to T from subprojects (`Repo<T>`) through the ServiceLoader
 * API. (Collects all `Repo<T>` instances that are declared in a subproject).
 *
 * @param default default mappings from T to their appropriate translation.
 * @param wraps parameter to declare which class this Serializer wraps. Needed for the collection of `Repo<T>`
 *     instances.
 */
class GenericKeyValueSerializer<T>(
    val wraps: Class<T>,
    val default: Map<T, String> = emptyMap(),
    val loadFromSubmodules: Boolean
) : JsonSerializer<T>() {

    val serializerMapping: Map<T, String> by lazy {
        collectSerializers()
    }

    /**
     * Collects all `Repo<T>` mappings of subprojects and the default ones.
     */
    private fun collectSerializers(): Map<T, String> {
        val result = mutableMapOf<T, String>()
        result.putAll(default)
        if (loadFromSubmodules) {
            val fromSubprojects = loadRepos(wraps)
            result.putAllReversed(fromSubprojects)
        }
        return result.toMap()
    }

    override fun serialize(
        value: T?,
        gen: JsonGenerator?,
        serializers: SerializerProvider?
    ) {
        if (gen != null && value != null) {
            val out = serializerMapping[value] ?: error("Unknown class: $value")
            gen.writeString(out)
        }
    }
}

private fun<T> MutableMap<String, T>.addAllPairs(repo: Repo<T>) {
    repo.getParameterSets().forEach { (key, value) ->
        val existing = putIfAbsent(key, value)
        if (existing != null) {
            error(
                "Duplicate Key-Value-Pair with key '$key' encountered. From " +
                    "Repo with name '${repo.name}'"
            )
        }
    }
}

private fun<T> Map<String, T>.reverseMapping(): Map<T, String> {
    val result = mutableMapOf<T, String>()
    result.putAllReversed(this)
    return result.toMap()
}

private fun<T> MutableMap<T, String>.putAllReversed(map: Map<String, T>) {
    map.forEach { (key, value) ->
        val existing = putIfAbsent(value, key)
        if (existing != null) {
            println(
                "[Warning]: Duplicate class to string mapping found for class  $value encountered. " +
                    "Mapping class  $value to ${get(value)} and ignoring all other string " +
                    "representations of that class for serialization."
            )
        }
    }
}

/**
 * Collects all registered `Repo<T>` of subprojects and collects their mappings together with the default ones.
 * @param loadFromSubmodules only searches for `Repo<T>` if this is set to true.
 * @return a map with the `default` pairs and
 */
private fun<T> collectMappings(wraps: Class<T>, default: Map<String, T>, loadFromSubmodules: Boolean): Map<String, T> {
    val result = mutableMapOf<String, T>()
    result.putAll(default)
    // 2. Discover and register from subprojects via ServiceLoader
    if (loadFromSubmodules) {
        result.loadRepos(wraps)
    }
    return result.toMap()
}

/**
 * Loads all `Repo<T>` from subprojects.
 * Inserts all mappings from the repos into the map.
 */
private fun<T> MutableMap<String, T>.loadRepos(wraps: Class<T>) {
    ServiceLoader.load(Repo::class.java)
        .forEach { repo ->
            if (repo.wraps == wraps) {
                println("Loading ${repo.name}")
                addAllPairs(repo as Repo<T>)
            }
        }
}

/**
 * Loads all `Repo<T>` from subprojects.
 * @return a map of all mappings found in registered `Repo<T>`.
 */
private fun<T> loadRepos(wraps: Class<T>): Map<String, T> {
    val result = mutableMapOf<String, T>()
    result.loadRepos(wraps)
    return result.toMap()
}
