package domain.jackson

import com.fasterxml.jackson.core.JsonGenerator
import com.fasterxml.jackson.core.JsonParser
import com.fasterxml.jackson.databind.DeserializationContext
import com.fasterxml.jackson.databind.JsonDeserializer
import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.JsonSerializer
import com.fasterxml.jackson.databind.SerializerProvider
import com.fasterxml.jackson.databind.module.SimpleModule
import java.util.ServiceLoader
import kotlin.collections.component1
import kotlin.collections.component2

/**
 * A builder for GenericKeyValueSerializers and Deserializers.
 * Collects all `Repo<T>` implementations from subprojects through the ServiceLoader
 * API (only if they are declared in the META-INF directory).
 *
 * @param default default mappings from strings to their appropriate translation.
 * @param wraps parameter to declare which class this Deserializer wraps. Needed for the collection of Repo<T>
 *     instances.
 */
class GenericKeyValueBuilder<T>(
    val wraps: Class<T>,
    val default: Map<String, T> = emptyMap(),
    val loadFromSubmodules: Boolean
) {

    val serializerMapping: Map<T, String> by lazy {
        deserializerMapping.map { (key, value) -> value to key }.toMap()
    }

    val deserializerMapping: Map<String, T> by lazy {
        collectMappings()
    }

    /**
     * Collects all deserializers of subprojects and the default ones.
     */
    private fun collectMappings(): Map<String, T> {
        val result = mutableMapOf<String, T>()
        result.putAll(default)
        // 2. Discover and register from subprojects via ServiceLoader
        if (loadFromSubmodules) {
            ServiceLoader.load(Repo::class.java)
                .forEach { parameterRepo ->
                    if (parameterRepo.wraps == wraps) {
                        println("Loading ${parameterRepo.name}")
                        parameterRepo.addAllPairs(result)
                    }
                }
        }
        return result.toMap()
    }

    fun getSerializer(): GenericKeyValueSerializer<T>  {
        return GenericKeyValueSerializer(
            wraps,
            serializerMapping,
            false
        )
    }

    fun getDeserializer(): GenericKeyValueDeserializer<T>  {
        return GenericKeyValueDeserializer(
            wraps,
            deserializerMapping,
            false
        )
    }

    /**
     * Creates a module containing both the serializer and deserializer that are generated by this class.
     */
    fun getModule(): SimpleModule {
        return SimpleModule("KeyValueSerializer of ${wraps}").run {
            addSerializer(wraps, getSerializer())
            addDeserializer(wraps, getDeserializer())
        }
    }
}

/**
 * Provides a simple deserializing from string to instance.
 * Collects all mappings from strings to T from subprojects through the ServiceLoader
 * API. (Collects all Repo<T> instances that are declared in a subproject).
 *
 * @param default default mappings from strings to their appropriate translation.
 * @param wraps parameter to declare which class this Deserializer wraps. Needed for the collection of Repo<T>
 *     instances.
 */
class GenericKeyValueDeserializer<T>(
    val wraps: Class<T>,
    val default: Map<String, T> = emptyMap(),
    val loadFromSubmodules: Boolean
) : JsonDeserializer<T>() {

    val mapping: Map<String, T> by lazy {
        collectDeserializers()
    }

    /**
     * Collects all deserializers of subprojects and the default ones.
     */
    private fun collectDeserializers(): Map<String, T> {
        val result = mutableMapOf<String, T>()
        result.putAll(default)
        // 2. Discover and register from subprojects via ServiceLoader
        if (loadFromSubmodules) {
            ServiceLoader.load(Repo::class.java)
                .forEach { parameterRepo ->
                    if (parameterRepo.wraps == wraps) {
                        println("Loading ${parameterRepo.name}")
                        parameterRepo.addAllPairs(result)
                    }
                }
        }
        return result.toMap()
    }

    override fun deserialize(
        p: JsonParser,
        ctxt: DeserializationContext?
    ): T {
        val node = p.codec.readTree<JsonNode>(p)

        val type = when {
            node.isTextual -> node.asText()
            else -> node.get("type").asText()
        }
        return mapping[type] ?: error("Unknown type: $type. Can't deserialize $type. " +
            "Known types: ${mapping.keys}")
    }
}

/**
 * Provides a simple serializing from instance to string.
 * Collects all mappings from string to T from subprojects (`Repo<T>`) through the ServiceLoader
 * API. (Collects all `Repo<T>` instances that are declared in a subproject).
 *
 * @param default default mappings from T to their appropriate translation.
 * @param wraps parameter to declare which class this Serializer wraps. Needed for the collection of `Repo<T>`
 *     instances.
 */
class GenericKeyValueSerializer<T>(
    val wraps: Class<T>,
    val default: Map<T, String> = emptyMap(),
    val loadFromSubmodules: Boolean
) : JsonSerializer<T>() {

    val serializerMapping: Map<T, String> by lazy {
        collectSerializers()
    }

    /**
     * Collects all `Repo<T>` mappings of subprojects and the default ones.
     */
    private fun collectSerializers(): Map<T, String> {
        val result = mutableMapOf<T, String>()
        result.putAll(default)
        // 2. Discover and register from subprojects via ServiceLoader
        if (loadFromSubmodules) {
            ServiceLoader.load(Repo::class.java)
                .forEach { parameterRepo ->
                    if (parameterRepo.wraps == wraps) {
                        println("Loading ${parameterRepo.name}")
                        parameterRepo.addPairsReversed(result)
                    }
                }
        }
        return result.toMap()
    }

    override fun serialize(
        value: T?,
        gen: JsonGenerator?,
        serializers: SerializerProvider?
    ) {
        if (gen != null && value != null) {
            val out = serializerMapping[value] ?: error("Unknown class: $value")
            gen.writeString(out)
        }
    }
}

interface Repo<T> {
    val name: String
    val wraps: Class<T>
    fun getParameterSets(): Map<String, T>
}

fun<T> Repo<*>.addAllPairs(map: MutableMap<String, T>) {
    getParameterSets().forEach { (key, value) ->
        val existing = map.putIfAbsent(key, value as T)
        if (existing != null) {
            error(
                "Duplicate Key-Value-Pair with key '$key' encountered. From " +
                    "Repo with name '$name'"
            )
        }
    }
}

fun<T> Repo<*>.addPairsReversed(map: MutableMap<T, String>) {
    getParameterSets().forEach { (key, value) ->
        val existing = map.putIfAbsent(value as T, key)
        if (existing != null) {
            error(
                "In Repo '$name': Duplicate class to string mapping found for class  $value encountered. " +
                        "Mapping class  $value to ${map[value]} and ignoring all other string " +
                        "representations of that class for serialization."
            )
        }
    }
}
