package domain.jackson

import com.fasterxml.jackson.core.JsonGenerator
import com.fasterxml.jackson.core.JsonParser
import com.fasterxml.jackson.core.JsonToken
import com.fasterxml.jackson.databind.BeanDescription
import com.fasterxml.jackson.databind.DeserializationConfig
import com.fasterxml.jackson.databind.DeserializationContext
import com.fasterxml.jackson.databind.JavaType
import com.fasterxml.jackson.databind.JsonDeserializer
import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.JsonSerializer
import com.fasterxml.jackson.databind.SerializationConfig
import com.fasterxml.jackson.databind.SerializerProvider
import com.fasterxml.jackson.databind.module.SimpleDeserializers
import com.fasterxml.jackson.databind.module.SimpleModule
import com.fasterxml.jackson.databind.module.SimpleSerializers
import com.fasterxml.jackson.databind.type.TypeFactory
import java.util.ServiceLoader
import kotlin.collections.component1
import kotlin.collections.component2
import kotlin.collections.forEach

/**
 * Subprojects need to implement this interface and register it in the `META-INF` directory, if they want to add mappings
 * to __existing__ KeyValueSerializers/Deserializers.
 *
 * @param type needs to be the exact JavaType of `T`. See the TypeFactory documentation on how to create a
 * [JavaType](https://fasterxml.github.io/jackson-databind/javadoc/2.10/com/fasterxml/jackson/databind/JavaType.html).
 */
interface Repo<T> {
    val name: String
    val type: JavaType
    fun getParameterSets(): Map<String, T>
}

/**
 * This class allows for granular filtering on when to apply the given `deserializer`.
 * @param targetType The type the deserializer matches against. Only if the passed type is the same or subtype of
 * the target type, this deserializer deserializes it (is returned as a matching deserializer).
 * @param deserializer A deserializer capable of serializing objects of the targetType.
 */
class SpecificTypeDeserializers(private val targetType: JavaType, private val deserializer: JsonDeserializer<*>) :
    SimpleDeserializers() {
    override fun findBeanDeserializer(
        type: JavaType,
        config: DeserializationConfig?,
        beanDesc: BeanDescription?
    ): JsonDeserializer<*>? {
        if (type.isSameOrSubtypeOf(targetType)) {
            return deserializer
        }
        return null
    }
}

/**
 * This class allows for granular filtering on when to apply the given `serializer`.
 * @param targetType The type the serializer matches against. Only if the passed object is the same or subtype of
 * the target type, this serializer serializes it.
 * @param serializer A serializer capable of serializing objects of the targetType.
 */
class SpecificTypeSerializers(private val targetType: JavaType, private val serializer: JsonSerializer<*>) :
    SimpleSerializers() {
    override fun findSerializer(
        config: SerializationConfig?,
        type: JavaType,
        beanDesc: BeanDescription?
    ): JsonSerializer<*>? {
        if (type.isSameOrSubtypeOf(targetType)) {
            return serializer
        }
        return null
    }
}

/**
 * A builder for GenericKeyValueSerializers and Deserializers.
 * Collects all `Repo<T>` implementations from subprojects through the ServiceLoader
 * API (only if they are declared in the `META-INF` directory).
 *
 * @param default default mappings from strings to their appropriate translation.
 * @param type parameter to declare which class this builder serializes and deserializes. `type` needs to be the exact
 * JavaType of `T`.
 */
class GenericKeyValueBuilder<T>(
    val type: JavaType,
    val default: Map<String, T> = emptyMap(),
    val loadFromSubmodules: Boolean
) {
    val serializerMapping: Map<T, String> by lazy {
        deserializerMapping.reverseMapping()
    }

    val deserializerMapping: Map<String, T> by lazy {
        collectMappings(type, default, loadFromSubmodules)
    }

    fun getSerializer(): GenericKeyValueSerializer<T> {
        return GenericKeyValueSerializer(
            type,
            serializerMapping,
            false
        )
    }

    fun getDeserializer(): GenericKeyValueDeserializer<T> {
        return GenericKeyValueDeserializer(
            type,
            deserializerMapping,
            false
        )
    }

    /**
     * Creates a module containing both the serializer and deserializer that are generated by this class.
     */
    fun getModule(): SimpleModule {
        return SimpleModule("KeyValueSerializer of $type").apply {
            setSerializers(SpecificTypeSerializers(
                type,
                getSerializer(),
            ))
            setDeserializers(SpecificTypeDeserializers(type, getDeserializer()))
        }
    }
}

/**
 * Provides a simple deserializing from string to instance.
 * Collects all mappings from strings to T from subprojects through the ServiceLoader
 * API. (Collects all Repo<T> instances that are declared in a subproject).
 *
 * @param default default mappings from strings to their appropriate translation.
 * @param type parameter to declare which class this Deserializer deserializes. `type` needs to be the exact
 * JavaType of `T`.
 */
class GenericKeyValueDeserializer<T>(
    val type: JavaType,
    val default: Map<String, T> = emptyMap(),
    val loadFromSubmodules: Boolean
) : JsonDeserializer<T>() {

    val mapping: Map<String, T> by lazy {
        collectMappings(type, default, loadFromSubmodules)
    }

    override fun deserialize(
        p: JsonParser,
        ctxt: DeserializationContext?
    ): T {
        if (p.currentToken() == JsonToken.START_OBJECT) {
            p.nextToken()
        }

        val node = p.codec.readTree<JsonNode>(p)

        val fieldValue = when {
            node.isTextual -> node.asText()
            else -> node.get("type").asText()
        }
        return mapping[fieldValue] ?: error("Unknown type: $fieldValue. Can't deserialize $fieldValue. " +
            "Known types: ${mapping.keys}")
    }
}

/**
 * Provides a simple serializing from instance to string.
 * Collects all mappings from string to T from subprojects (`Repo<T>`) through the ServiceLoader
 * API. (Collects all `Repo<T>` instances that are declared in a subproject).
 *
 * @param default default mappings from T to their appropriate translation.
 * @param type parameter to declare which class this Serializer serializes. `type` needs to be the exact
 * JavaType of `T`.
 */
class GenericKeyValueSerializer<T>(
    val type: JavaType,
    val default: Map<T, String> = emptyMap(),
    val loadFromSubmodules: Boolean,
) : JsonSerializer<T>() {

    val serializerMapping: Map<T, String> by lazy {
        collectSerializers()
    }

    /**
     * Collects all `Repo<T>` mappings of subprojects and the default ones.
     */
    private fun collectSerializers(): Map<T, String> {
        val result = mutableMapOf<T, String>()
        result.putAll(default)
        if (loadFromSubmodules) {
            val fromSubprojects = loadRepos<T>(type)
            result.putAllReversed(fromSubprojects)
        }
        return result.toMap()
    }

    override fun serialize(
        value: T?,
        gen: JsonGenerator?,
        serializers: SerializerProvider?
    ) {
        if (gen != null && value != null) {
            val out = serializerMapping[value] ?: error("Unknown class: $value")
            gen.writeString(out)
        }
    }
}

private fun<T> MutableMap<String, T>.addAllPairs(repo: Repo<T>) {
    repo.getParameterSets().forEach { (key, value) ->
        val existing = putIfAbsent(key, value)
        if (existing != null) {
            error(
                "Duplicate Key-Value-Pair with key '$key' encountered. From " +
                    "Repo with name '${repo.name}'"
            )
        }
    }
}

private fun<T> Map<String, T>.reverseMapping(): Map<T, String> {
    val result = mutableMapOf<T, String>()
    result.putAllReversed(this)
    return result.toMap()
}

private fun<T> MutableMap<T, String>.putAllReversed(map: Map<String, T>) {
    map.forEach { (key, value) ->
        val existing = putIfAbsent(value, key)
        if (existing != null) {
            println(
                "[Warning]: Duplicate class to string mapping found for class  $value encountered. " +
                    "Mapping class  $value to ${get(value)} and ignoring all other string " +
                    "representations of that class for serialization."
            )
        }
    }
}

/**
 * Collects all registered `Repo<T>` of subprojects and collects their mappings together with the default ones.
 * @param loadFromSubmodules only searches for `Repo<T>` if this is set to true.
 * @return a map with the `default` pairs and
 */
private fun<T> collectMappings(type: JavaType, default: Map<String, T>, loadFromSubmodules: Boolean): Map<String, T> {
    val result = mutableMapOf<String, T>()
    result.putAll(default)
    // 2. Discover and register from subprojects via ServiceLoader
    if (loadFromSubmodules) {
        result.loadRepos(type)
    }
    return result.toMap()
}

/**
 * Loads all `Repo<T>` from subprojects.
 * Inserts all mappings from the repos into the map.
 */
private fun<T> MutableMap<String, T>.loadRepos(type: JavaType) {
    ServiceLoader.load(Repo::class.java)
        .forEach { repo ->
            if (repo.type.isSameOrSubtypeOf(type)) {
                println("Loading ${repo.name}")
                addAllPairs(repo as Repo<T>)
            }
        }
}

/**
 * Loads all `Repo<T>` from subprojects.
 * @return a map of all mappings found in registered `Repo<T>`.
 */
private fun<T> loadRepos(type: JavaType): Map<String, T> {
    val result = mutableMapOf<String, T>()
    result.loadRepos(type)
    return result.toMap()
}

/**
 * @return true if both are the same type or `this` is a subtype of `other`.
 */
fun JavaType.isSameOrSubtypeOf(other: JavaType): Boolean {
    return this == other || other in this.interfaces || this.isSubtypeOf(other)
}

/**
 * @return true if `this` is a subtype of `other`.
 */
fun JavaType.isSubtypeOf(other: JavaType): Boolean {
    var current = this
    while (current.superClass != null) {
        if (current.superClass.isSameOrSubtypeOf(other)) return true
        current = current.superClass
    }
    return false
}

/**
 * Helper for JavaType creation.
 *
 *
 * If you want to get the JavaType of a parameterized type like `A<B>` use this instead:
 * ```kotlin
 * TypeFactory.defaultInstance().constructParametricType(A::class.java, B::class.java)
 * ```
 */
fun javaType(type: Class<*>): JavaType {
    return TypeFactory.defaultInstance().constructType(type)
}
